version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: movieapp
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
